import Foundation

/// Scans macOS 4K/8K Aerial video wallpapers, application caches, diagnostic logs, and Xcode/developer caches.
public enum SystemAndDevJunkScanner {
    
    public static func scan(
        homeDirectory: URL = FileManager.default.homeDirectoryForCurrentUser
    ) -> [ScanItem] {
        var results: [ScanItem] = []
        
        // 1. macOS Aerial Video Wallpapers & Wallpaper Stores
        results.append(contentsOf: scanWallpaperStores(homeDirectory: homeDirectory))
        
        // 2. Developer & Xcode Caches in ~/Library/Developer and ~/Library/Caches
        results.append(contentsOf: scanDeveloperLocations(homeDirectory: homeDirectory))
        
        // 3. User Application & Browser Caches (~/Library/Caches/*)
        results.append(contentsOf: scanApplicationCaches(homeDirectory: homeDirectory))
        
        // 4. Logs & Diagnostic Reports (~/Library/Logs/* & ~/Library/DiagnosticReports)
        results.append(contentsOf: scanLogsAndDiagnostics(homeDirectory: homeDirectory))
        
        return results.sorted { $0.sizeBytes > $1.sizeBytes }
    }
    
    // MARK: - 1. Wallpapers
    
    private static func scanWallpaperStores(homeDirectory: URL) -> [ScanItem] {
        let fm = FileManager.default
        var items: [ScanItem] = []
        
        let candidates: [(url: URL, title: String, explanation: String)] = [
            (
                URL(fileURLWithPath: "/Library/Application Support/com.apple.idleassetsd/Customer/4KSDR240FPS"),
                "macOS 4K 240FPS Aerial Video Wallpapers",
                "High-bitrate 4K/240fps video wallpapers and screensavers automatically downloaded by macOS. Safe to delete; macOS re-downloads active wallpapers on demand."
            ),
            (
                URL(fileURLWithPath: "/Library/Application Support/com.apple.idleassetsd/Customer"),
                "macOS Aerial Wallpaper Assets (idleassetsd)",
                "System video wallpaper asset store. Contains downloaded Aerial video packs that often consume 5–50 GB."
            ),
            (
                homeDirectory.appendingPathComponent("Library/Application Support/com.apple.wallpaper"),
                "User Wallpaper Cache & Dynamic Desktop Assets",
                "Cached wallpaper renders and dynamic desktop metadata in your user Library."
            )
        ]
        
        var seenPaths: Set<String> = []
        for candidate in candidates {
            if Task.isCancelled { break }
            let path = candidate.url.standardizedFileURL.path
            if seenPaths.contains(where: { $0.hasPrefix(path + "/") || path.hasPrefix($0 + "/") }) {
                continue
            }
            guard fm.fileExists(atPath: path) else { continue }
            
            let metrics = DiskSizeCalculator.calculateMetrics(
                at: candidate.url,
                maxFiles: 3_000,
                includeChildrenForCategory: .wallpapersAndMedia,
                parentSafety: .safe,
                maxChildren: 12
            )
            guard metrics.sizeBytes >= 512 * 1024 else { continue }
            
            seenPaths.insert(path)
            
            items.append(
                ScanItem(
                    url: candidate.url,
                    name: candidate.title,
                    sizeBytes: metrics.sizeBytes,
                    category: .wallpapersAndMedia,
                    safetyLevel: .safe,
                    explanation: candidate.explanation,
                    associatedAppName: "macOS Wallpaper Engine",
                    isOrphaned: false,
                    isDirectory: true,
                    lastModified: metrics.lastModified,
                    fileCount: metrics.fileCount,
                    isSelected: true,
                    children: metrics.children
                )
            )
        }
        
        return items
    }
    
    // MARK: - 2. Developer & Xcode Caches
    
    private static func scanDeveloperLocations(homeDirectory: URL) -> [ScanItem] {
        let fm = FileManager.default
        var items: [ScanItem] = []
        
        let devTargets: [(relativePath: String, title: String, safety: SafetyLevel, explanation: String)] = [
            (
                "Library/Developer/Xcode/DerivedData",
                "Xcode DerivedData (Build Intermediates & Indexes)",
                .safe,
                "Intermediate build artifacts and symbol indexes generated by Xcode. Completely safe to delete; Xcode rebuilds active projects when compiled."
            ),
            (
                "Library/Developer/Xcode/iOS DeviceSupport",
                "Xcode iOS DeviceSupport Symbols",
                .safe,
                "Debug symbols downloaded from connected iPhones/iPads. Often 5–30 GB; Xcode re-extracts symbols only if a device is attached for debugging."
            ),
            (
                "Library/Developer/Xcode/Archives",
                "Xcode Release Archives (.xcarchive)",
                .review,
                "Historical release build archives created in Xcode. Review before deleting if you need old dSYMs."
            ),
            (
                "Library/Developer/CoreSimulator/Caches",
                "iOS/watchOS Simulator Caches",
                .safe,
                "Temporary caches generated by Xcode CoreSimulator runtimes."
            ),
            (
                "Library/Caches/Homebrew",
                "Homebrew Package Download Cache",
                .safe,
                "Downloaded .tar.gz / .bottle installers cached by Homebrew. Safe to remove without affecting installed formulas."
            ),
            (
                "Library/Caches/pip",
                "Python pip Wheel & Package Cache",
                .safe,
                "Cached Python wheel archives downloaded by pip."
            ),
            (
                "Library/Caches/ms-playwright",
                "Playwright Headless Browser Binaries",
                .safe,
                "Downloaded Chromium/Firefox/WebKit binaries used by Playwright automated tests (often 1–3 GB)."
            ),
            (
                "Library/Caches/Google/AndroidStudio",
                "Android Studio IDE Cache",
                .safe,
                "Temporary index and build caches for Android Studio."
            )
        ]
        
        for target in devTargets {
            if Task.isCancelled { break }
            let url = homeDirectory.appendingPathComponent(target.relativePath)
            guard fm.fileExists(atPath: url.path) else { continue }
            
            let metrics = DiskSizeCalculator.calculateMetrics(
                at: url,
                maxFiles: 4_500,
                includeChildrenForCategory: .developerAndAICaches,
                parentSafety: target.safety,
                maxChildren: 10
            )
            guard metrics.sizeBytes >= 1 * 1024 * 1024 else { continue }
            
            items.append(
                ScanItem(
                    url: url,
                    name: target.title,
                    sizeBytes: metrics.sizeBytes,
                    category: .developerAndAICaches,
                    safetyLevel: target.safety,
                    explanation: target.explanation,
                    associatedAppName: "Developer Tools",
                    isOrphaned: false,
                    isDirectory: true,
                    lastModified: metrics.lastModified,
                    fileCount: metrics.fileCount,
                    isSelected: target.safety.defaultSelected,
                    children: metrics.children
                )
            )
        }
        
        return items
    }
    
    // MARK: - 3. Application & Browser Caches
    
    private static func scanApplicationCaches(homeDirectory: URL) -> [ScanItem] {
        let fm = FileManager.default
        let cachesRoot = homeDirectory.appendingPathComponent("Library/Caches")
        guard let entries = try? fm.contentsOfDirectory(
            at: cachesRoot,
            includingPropertiesForKeys: [.isDirectoryKey, .isSymbolicLinkKey],
            options: [.skipsHiddenFiles]
        ) else {
            return []
        }
        
        let skippedNames: Set<String> = [
            "homebrew", "pip", "ms-playwright", "cloudkit", "com.apple.findmy.fmfcore",
            "com.apple.icloud.fmfd", "com.apple.ap.adprivacyd", "familycircle"
        ]
        
        var items: [ScanItem] = []
        for url in entries {
            if Task.isCancelled { break }
            let name = url.lastPathComponent
            if skippedNames.contains(name.lowercased()) || TCCGuard.shouldSkipTraversal(of: url) {
                continue
            }
            
            guard let values = try? url.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey]),
                  values.isSymbolicLink != true else {
                continue
            }
            
            let isDir = values.isDirectory == true
            let metrics = DiskSizeCalculator.calculateMetrics(
                at: url,
                maxFiles: 3_000,
                includeChildrenForCategory: isDir ? .appAndBrowserCaches : nil,
                parentSafety: .safe,
                maxChildren: 8
            )
            guard metrics.sizeBytes >= 2 * 1024 * 1024 else { continue }
            
            items.append(
                ScanItem(
                    url: url,
                    name: name,
                    sizeBytes: metrics.sizeBytes,
                    category: .appAndBrowserCaches,
                    safetyLevel: .safe,
                    explanation: "Temporary cache folder in ~/Library/Caches/\(name). Safe to delete; the application recreates cached files automatically.",
                    associatedAppName: name,
                    isOrphaned: false,
                    isDirectory: isDir,
                    lastModified: metrics.lastModified,
                    fileCount: metrics.fileCount,
                    isSelected: true,
                    children: metrics.children
                )
            )
        }
        
        return items
    }
    
    // MARK: - 4. Logs & Diagnostic Reports
    
    private static func scanLogsAndDiagnostics(homeDirectory: URL) -> [ScanItem] {
        let fm = FileManager.default
        var items: [ScanItem] = []
        
        let logRoot = homeDirectory.appendingPathComponent("Library/Logs")
        guard let entries = try? fm.contentsOfDirectory(
            at: logRoot,
            includingPropertiesForKeys: [.isDirectoryKey, .isSymbolicLinkKey],
            options: [.skipsHiddenFiles]
        ) else {
            return []
        }
        
        for entryURL in entries {
            if Task.isCancelled { break }
            if TCCGuard.shouldSkipTraversal(of: entryURL) { continue }
            
            guard let values = try? entryURL.resourceValues(forKeys: [.isDirectoryKey, .isSymbolicLinkKey]),
                  values.isSymbolicLink != true else {
                continue
            }
            
            let metrics = DiskSizeCalculator.calculateMetrics(at: entryURL, maxFiles: 2_000)
            guard metrics.sizeBytes >= 512 * 1024 else { continue }
            
            items.append(
                ScanItem(
                    url: entryURL,
                    name: entryURL.lastPathComponent,
                    sizeBytes: metrics.sizeBytes,
                    category: .logsAndDiagnostics,
                    safetyLevel: .safe,
                    explanation: "Application log in ~/Library/Logs. Safe to delete; logs are only used for troubleshooting.",
                    associatedAppName: entryURL.lastPathComponent,
                    isOrphaned: false,
                    isDirectory: values.isDirectory == true,
                    lastModified: metrics.lastModified,
                    fileCount: metrics.fileCount,
                    isSelected: true
                )
            )
        }
        
        return items
    }
}
